version: '3'

services:

  backend:
    build:
      context: ./express3015
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./react3015
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
volumes:
  datafiles: